### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Th3AL0** [8balljunkie/ohatv#1]
He

how do the settings work with bittorrent?

Gr

**Comment by 8balljunkie** [comment]
Go to settings and do the following:
Select a client for now the only supported client is Transmission webui with no login.
The url is something like http://ipaddress:port/transmission/rpc

Blackhole means it's going to download the torrent file and place it in a folder.
In your bittorrent client you will let it monitor that folder for new torrent files.

The working folder is the place where it will download the files and torrents.
For blackhole set your bittorrent client to download to that folder.
On Windows you will need to type something like c:\downloadfolder
On Mac or Linux it's like /home/user/Downloads

Process to folder
Is the folder where it will process your files from the download folder
On Windows you will need to type something like c:\Processfolder
On Mac or Linux it's like /home/user/Processfolder

If you have any problems regarding the settings please give your bittorrent client and Operating system.
I added some screenshots for help.
![1](https://cloud.githubusercontent.com/assets/3928934/8889206/c8996c9c-32d0-11e5-8e47-109b8a66dd2b.PNG)
